# gameplay balance config: health, damage, speed, cooldowns

from .base import TILE_SIZE, GroundMaterial, ItemType, ObjectType

# Mapping of ground material to time needed to mine (seconds)
MATERIAL_TO_MINE_TIME = {
    GroundMaterial.STONE: 0.3,
    GroundMaterial.COPPER: 0.6,
    GroundMaterial.HARD_STONE: 0.8,
}

# Mapping of entity types to mining efficiency multiplier
ENTITY_TO_MINE_EFFICIENCY = {
    ObjectType.DRILL: 2.0,
    ObjectType.DRONE: 1.0,
}

# Small random variation applied to mining time per tick
MINE_TIME_SPREAD = 0.05


# --- player ---
DRONE_HEALTH = 30
DRONE_MAX_SPEED = TILE_SIZE * 15
DRONE_DECELERATION = TILE_SIZE * 0.25
DRONE_ACCELERATION = TILE_SIZE * 1.0 + DRONE_DECELERATION

DRONE_SIZE = (1.5 * TILE_SIZE, 1.5 * TILE_SIZE)
DRONE_SPAWN_POS = (-DRONE_SIZE[0] // 2, -DRONE_SIZE[1] // 2)
MINE_REACH_DIST = TILE_SIZE * 1.5
DRONE_SHOOT_COOLDOWN = 0.2  # seconds between shots

DRILL_HP_PER_PATCH = 15
BULLETS_PER_COPPER = 5

INITIALLY_ALLOCATED_RESOURCES = {
    ItemType.COPPER: 10,
    # ItemType.BULLET: 0,
    # ItemType.PATCH: 0,
}


# --- drill ---
DRILL_HEALTH = 1000
DRILL_MAX_SPEED = TILE_SIZE * 3
DRILL_ACCELERATION = TILE_SIZE * 0.1
DRILL_DECELERATION = TILE_SIZE * 0.2

DRILL_SIZE = (TILE_SIZE * 7, TILE_SIZE * 15)
DRILL_SPAWN_POS = (-DRILL_SIZE[0] // 2, -DRILL_SIZE[1] - 3 * TILE_SIZE)


# --- projectile ---
PROJECTILE_SPEED = TILE_SIZE * 25
PROJECTILE_LIFETIME = 10.0
PROJECTILE_INHERIT_PLAYER_VELOCITY = 0.7
PROJECTILE_DAMAGE = 20

PROJECTILE_SIZE = (TILE_SIZE // 4, TILE_SIZE // 4)


# --- enemy ---
ENEMY_HEALTH = 50
ENEMY_CONTACT_DAMAGE = 10
ENEMY_DAMAGE_COOLDOWN_SEC = 1.5
ENEMY_DECELERATION = TILE_SIZE * 0.1
ENEMY_MAX_SPEED = TILE_SIZE * 3
ENEMY_ACCELERATION = TILE_SIZE * 0.2

ENEMY_NOTICING_RADIUS = TILE_SIZE * 20
ENEMY_LOSES_PLAYER_RADIUS = TILE_SIZE * 30

ENEMY_SIZE = (TILE_SIZE * 0.8, TILE_SIZE * 0.8)


# --- combat ---
KNOCKBACK_FORCE = TILE_SIZE * 8
ENTITY_WEIGHT_MAP = {
    ObjectType.DRILL: 4.0,
    ObjectType.DRONE: 0.8,
    ObjectType.ENEMY: 0.4,
}
VELOCITY_LOSS_ON_DAMAGE = 0.2
PLAYER_RESPAWN_TIME = 5 # seconds


# --- physics ---
# multiply velocity by it every frame when collided with the wall
VELOCITY_LOSS_ON_COLLISION = 0.75
SOFT_COLLISION_FORCE = TILE_SIZE * 0.5

OBJECT_TO_SIZE = {
    ObjectType.DRILL: DRILL_SIZE,
    ObjectType.DRONE: DRONE_SIZE,
    ObjectType.ENEMY: ENEMY_SIZE,
    ObjectType.PROJECTILE: PROJECTILE_SIZE,
    ObjectType.GROUND: (TILE_SIZE, TILE_SIZE),
}


# ores
COPPER_NOISE_SIZE = 4
COPPER_NOISE_THRESHOLD = 0.4

HARD_STONE_NOISE_SIZE = 15
HARD_STONE_NOISE_THRESHOLD = 0.3