# gameplay balance config: health, damage, speed, cooldowns

from .base import TILE_SIZE, ItemType, ObjectType


# --- player ---
DRONE_HEALTH = 30
DRONE_MAX_SPEED = TILE_SIZE * 15
DRONE_ACCELERATION = TILE_SIZE * 1.0
DRONE_DECELERATION = TILE_SIZE * 0.25

MINE_REACH_DIST = TILE_SIZE * 1.5

DRILL_HP_PER_PATCH = 15
BULLETS_PER_COPPER = 5

INITIALLY_ALLOCATED_RESOURCES = {
    ItemType.COPPER: 10,
    # ItemType.BULLET: 0,
    # ItemType.PATCH: 0,
}


# --- drill ---
DRILL_HEALTH = 1000
DRILL_MAX_SPEED = TILE_SIZE * 5
DRILL_ACCELERATION = TILE_SIZE * 0.1
DRILL_DECELERATION = TILE_SIZE * 0.2


# --- projectile ---
PROJECTILE_SPEED = TILE_SIZE * 25
PROJECTILE_LIFETIME = 10.0
PROJECTILE_INHERIT_PLAYER_VELOCITY = 0.7
PROJECTILE_DAMAGE = 20


# --- enemy ---
ENEMY_HEALTH = 50
ENEMY_CONTACT_DAMAGE = 10
ENEMY_DAMAGE_COOLDOWN_SEC = 1.5
ENEMY_DECELERATION = TILE_SIZE * 0.1
ENEMY_MAX_SPEED = TILE_SIZE * 3
ENEMY_ACCELERATION = TILE_SIZE * 0.2
ENEMY_VISION_RADIUS = TILE_SIZE * 15

ENEMY_SPAWN_PER_CAVE_RANGE = (0, 3)
ENEMY_SPAWN_MIN_DISTANCE_FROM_CAVE_START = 15  # in tiles


# --- combat ---
KNOCKBACK_FORCE = TILE_SIZE * 8
ENTITY_WEIGHT_MAP = {
    ObjectType.DRILL: 4.0,
    ObjectType.DRONE: 0.8,
    ObjectType.ENEMY: 0.4,
}
VELOCITY_LOSS_ON_HIT = 0.2  # keep 20% of velocity when hit
PLAYER_RESPAWN_TIME = 5 # seconds


# --- physics ---
# multiply velocity by it every frame when collided with the wall
VELOCITY_LOSS_ON_COLLISION = 0.75


# --- caves ---
CAVE_SPAWN_CHANCE_BASE = 0.05
CAVE_MIN_TILES_BETWEEN = 100
CAVE_LENGTH_RANGE = (20, 40)
CAVE_THICKNESS_RANGE = (1.5, 3.0)
CAVE_MAX_ANGLE_CHANGE = 30  # degrees
THICKNESS_CONTROL_POINTS_NUM_RANGE = (1, 3)
