# settings for cave generation

SPAWN_CHANCE_BASE = 0.05
MIN_TILES_BETWEEN = 250

ENEMY_SPAWN_PER_TILE = 0.02


MAIN_CAVE_SCALE_RANGE = (5, 8)
MAIN_CAVE_THRESHOLD_RANGE = (0.1, 0.3)

VEIN_SCALE_X_RANGE = (10, 50)
VEIN_SCALE_Y_RANGE = (2, 8)
VEIN_ANGLE_RANGE = (0, 180)
VEIN_THRESHOLD_RANGE = (0.2, 0.5)


NOISE_START_SEARCH_TRIES = 50

GEN_OFFSET_TRIES = 3
GEN_MIN_TRY_DISTANCE_TILES = 20
GEN_TRY_OFFSET_TILES = 10
GEN_TRY_OFFSET_SPREAD_TILES = 10

MAX_RECURSON_DEPTH = 100


